'use strict';

const players = [
  {
    name: 'Alex Kyalo',
    email: 'AlexKyalo@gmail.com',
    username: 'AlexKyalo',
    phoneNumber: '1',
    playerLevel: '1',
    isVirtual: true,
    password: 'AlexKyalo@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Brian Kipkoech',
    email: 'BrianKipkoech@gmail.com',
    username: 'BrianKipkoech',
    phoneNumber: '2',
    playerLevel: '2',
    isVirtual: true,
    password: 'BrianKipkoech@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Sherile Kapsukut',
    email: 'SherileKapsukut@gmail.com',
    username: 'SherileKapsukut',
    phoneNumber: '3',
    playerLevel: '3',
    isVirtual: true,
    password: 'SherileKapsukut@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'VICTOR MARTIN',
    email: 'VICTORMARTIN@gmail.com',
    username: 'VICTORMARTIN',
    phoneNumber: '4',
    playerLevel: '4',
    isVirtual: true,
    password: 'VICTORMARTIN@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Cynthia Ngumo',
    email: 'CynthiaNgumo@gmail.com',
    username: 'CynthiaNgumo',
    phoneNumber: '5',
    playerLevel: '5',
    isVirtual: true,
    password: 'CynthiaNgumo@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Evans Mogeni',
    email: 'EvansMogeni@gmail.com',
    username: 'EvansMogeni',
    phoneNumber: '6',
    playerLevel: '1',
    isVirtual: true,
    password: 'EvansMogeni@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Benjamin Charles',
    email: 'BenjaminCharles@gmail.com',
    username: 'BenjaminCharles',
    phoneNumber: '7',
    playerLevel: '2',
    isVirtual: true,
    password: 'BenjaminCharles@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Eric Mbatia',
    email: 'EricMbatia@gmail.com',
    username: 'EricMbatia',
    phoneNumber: '8',
    playerLevel: '3',
    isVirtual: true,
    password: 'EricMbatia@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'John Njau',
    email: 'JohnNjau@gmail.com',
    username: 'JohnNjau',
    phoneNumber: '9',
    playerLevel: '4',
    isVirtual: true,
    password: 'JohnNjau@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Josphat Niaru',
    email: 'JosphatNiaru@gmail.com',
    username: 'JosphatNiaru',
    phoneNumber: '10',
    playerLevel: '5',
    isVirtual: true,
    password: 'JosphatNiaru@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Meshack Bosire',
    email: 'MeshackBosire@gmail.com',
    username: 'MeshackBosire',
    phoneNumber: '11',
    playerLevel: '1',
    isVirtual: true,
    password: 'MeshackBosire@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Anthony Mwangi',
    email: 'AnthonyMwangi@gmail.com',
    username: 'AnthonyMwangi',
    phoneNumber: '12',
    playerLevel: '2',
    isVirtual: true,
    password: 'AnthonyMwangi@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Edwin Atieno',
    email: 'EdwinAtieno@gmail.com',
    username: 'EdwinAtieno',
    phoneNumber: '13',
    playerLevel: '3',
    isVirtual: true,
    password: 'EdwinAtieno@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Emmanuel Chalo',
    email: 'EmmanuelChalo@gmail.com',
    username: 'EmmanuelChalo',
    phoneNumber: '14',
    playerLevel: '4',
    isVirtual: true,
    password: 'EmmanuelChalo@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Rahab Mary',
    email: 'RahabMary@gmail.com',
    username: 'RahabMary',
    phoneNumber: '15',
    playerLevel: '5',
    isVirtual: true,
    password: 'RahabMary@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'alex karani',
    email: 'alexkarani@gmail.com',
    username: 'alexkarani',
    phoneNumber: '16',
    playerLevel: '1',
    isVirtual: true,
    password: 'alexkarani@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'cosmas thuku',
    email: 'cosmasthuku@gmail.com',
    username: 'cosmasthuku',
    phoneNumber: '17',
    playerLevel: '2',
    isVirtual: true,
    password: 'cosmasthuku@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Meshack Kimwele',
    email: 'MeshackKimwele@gmail.com',
    username: 'MeshackKimwele',
    phoneNumber: '18',
    playerLevel: '3',
    isVirtual: true,
    password: 'MeshackKimwele@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Osuka Savin',
    email: 'OsukaSavin@gmail.com',
    username: 'OsukaSavin',
    phoneNumber: '19',
    playerLevel: '4',
    isVirtual: true,
    password: 'OsukaSavin@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Lawrence Kyalo',
    email: 'LawrenceKyalo@gmail.com',
    username: 'LawrenceKyalo',
    phoneNumber: '20',
    playerLevel: '5',
    isVirtual: true,
    password: 'LawrenceKyalo@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Gwendolyn Amanda',
    email: 'GwendolynAmanda@gmail.com',
    username: 'GwendolynAmanda',
    phoneNumber: '21',
    playerLevel: '1',
    isVirtual: true,
    password: 'GwendolynAmanda@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Daniel Mwangi',
    email: 'DanielMwangi@gmail.com',
    username: 'DanielMwangi',
    phoneNumber: '22',
    playerLevel: '2',
    isVirtual: true,
    password: 'DanielMwangi@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'David Karanja',
    email: 'DavidKaranja@gmail.com',
    username: 'DavidKaranja',
    phoneNumber: '23',
    playerLevel: '3',
    isVirtual: true,
    password: 'DavidKaranja@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Lennox Namasaka',
    email: 'LennoxNamasaka@gmail.com',
    username: 'LennoxNamasaka',
    phoneNumber: '24',
    playerLevel: '4',
    isVirtual: true,
    password: 'LennoxNamasaka@gmail.com',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */
   await queryInterface.bulkInsert('Users', players, {});
  },

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    await queryInterface.bulkDelete('Users', null, {});
  }
};
